// YouTube Transcript API Handler
class YouTubeTranscriptAPI {
    constructor() {
        this.apiBase = 'http://localhost:3000/api';
    }

    /**
     * Extract video ID from various YouTube URL formats
     */
    extractVideoId(url) {
        const patterns = [
            /(?:youtube\.com\/watch\?v=|youtu\.be\/)([^&\n?#]+)/,
            /youtube\.com\/embed\/([^&\n?#]+)/,
            /youtube\.com\/v\/([^&\n?#]+)/,
            /youtube\.com\/shorts\/([^&\n?#]+)/
        ];
        
        for (const pattern of patterns) {
            const match = url.match(pattern);
            if (match && match[1]) return match[1];
        }
        return null;
    }

    /**
     * Fetch video metadata using oEmbed API
     */
    async getVideoMetadata(videoId) {
        try {
            const response = await fetch(`https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`);
            const data = await response.json();
            
            return {
                title: data.title || 'Unknown Title',
                channel: data.author_name || 'Unknown Channel',
                thumbnail: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
                videoId
            };
        } catch (error) {
            console.error('Error fetching metadata:', error);
            return {
                title: 'Video Title',
                channel: 'Channel Name',
                thumbnail: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
                videoId
            };
        }
    }

    /**
     * Fetch transcript from backend
     */
    async getTranscript(videoId, lang = null) {
        try {
            const url = lang 
                ? `${this.apiBase}/transcript/${videoId}?lang=${lang}`
                : `${this.apiBase}/transcript/${videoId}`;
            
            console.log('Fetching from:', url);
            
            const response = await fetch(url);
            console.log('Response status:', response.status);
            
            const data = await response.json();
            console.log('Response data:', data);
            
            if (!data.success) {
                throw new Error(data.error || 'Failed to fetch transcript');
            }
            
            console.log('Transcript items:', data.transcript.length);
            return data.transcript;
        } catch (error) {
            console.error('Error fetching transcript:', error);
            throw error;
        }
    }

    /**
     * Main method to get full transcript
     */
    async fetchFullTranscript(videoUrl) {
        const videoId = this.extractVideoId(videoUrl);
        if (!videoId) {
            throw new Error('Invalid YouTube URL');
        }

        try {
            // Fetch metadata and transcript
            const metadata = await this.getVideoMetadata(videoId);
            const transcript = await this.getTranscript(videoId);

            // Create language options (simplified for now)
            const availableLanguages = [
                { languageCode: 'en', name: 'English', isAutoGenerated: false }
            ];

            return {
                metadata,
                availableLanguages,
                transcript,
                videoId
            };
        } catch (error) {
            console.error('Error in fetchFullTranscript:', error);
            throw error;
        }
    }

    /**
     * Fetch transcript in specific language
     */
    async fetchTranscriptByLanguage(videoId, languageCode) {
        return await this.getTranscript(videoId, languageCode);
    }
}

// Export for use in main script
window.YouTubeTranscriptAPI = YouTubeTranscriptAPI;
