let birthdays=JSON.parse(localStorage.getItem('birthdays'))||[];function addBirthday(){const name=document.getElementById('nameInput').value.trim();const date=document.getElementById('dateInput').value;if(!name||!date){alert('Please fill all fields!');return}birthdays.push({id:Date.now(),name,date,created:new Date().toISOString()});saveBirthdays();renderBirthdays();document.getElementById('nameInput').value='';document.getElementById('dateInput').value=''}function deleteBirthday(id){if(confirm('Delete this birthday?')){birthdays=birthdays.filter(b=>b.id!==id);saveBirthdays();renderBirthdays()}}function renderBirthdays(){const list=document.getElementById('birthdaysList');const today=new Date();today.setHours(0,0,0,0);const sorted=[...birthdays].sort((a,b)=>{const daysA=getDaysUntil(a.date);const daysB=getDaysUntil(b.date);return daysA-daysB});if(sorted.length===0){list.innerHTML='<div class="no-birthdays">No birthdays added yet</div>';return}list.innerHTML=sorted.map(b=>{const days=getDaysUntil(b.date);const isToday=days===0;const isSoon=days>0&&days<=7;return`
<div class="birthday-card ${isToday?'today':isSoon?'soon':''}">
<div class="birthday-info">
<div class="birthday-name">${b.name}</div>
<div class="birthday-date">${formatDate(b.date)}</div>
<div class="birthday-countdown">${isToday?'🎉 Today!':days<0?`${Math.abs(days)} days ago`:`In ${days} days`}</div>
</div>
<button onclick="deleteBirthday(${b.id})" class="btn-delete">Delete</button>
</div>
`}).join('')}function getDaysUntil(dateStr){const today=new Date();today.setHours(0,0,0,0);const bday=new Date(dateStr);const thisYear=new Date(today.getFullYear(),bday.getMonth(),bday.getDate());if(thisYear<today){thisYear.setFullYear(today.getFullYear()+1)}return Math.ceil((thisYear-today)/(1000*60*60*24))}function formatDate(dateStr){const d=new Date(dateStr);return d.toLocaleDateString('en-US',{month:'long',day:'numeric'})}function saveBirthdays(){localStorage.setItem('birthdays',JSON.stringify(birthdays))}renderBirthdays();console.log('🎂 Birthday Reminder Ready');
