// Additional problems data - extending each category with more problems
const additionalProblems = {
    tech: [
        { title: 'Best smartphone under $500 in 2024?', solutions: ['Google Pixel 7a - Best camera, clean Android', 'Samsung Galaxy A54 - Great display, battery', 'OnePlus Nord 3 - Fast charging, good performance', 'Motorola Edge 40 - Stock Android experience', 'Nothing Phone 2a - Unique design, good value'] },
        { title: 'How to speed up slow Windows PC?', solutions: ['Disable startup programs in Task Manager', 'Run Disk Cleanup and defragment', 'Upgrade to SSD if using HDD', 'Disable visual effects for performance', 'Uninstall bloatware and unused programs'] },
        { title: 'Best free antivirus for Windows?', solutions: ['Windows Defender - Built-in, free, effective', 'Malwarebytes - Great for malware removal', 'Bitdefender Free - Excellent protection', 'Kaspersky Free - Strong security features', 'Avast Free - Comprehensive protection'] },
        { title: 'How to recover deleted files?', solutions: ['Check Recycle Bin first', 'Use Recuva or EaseUS recovery software', 'Stop using drive immediately to prevent overwrite', 'Try Windows File History if enabled', 'Professional data recovery service for critical files'] },
        { title: 'Best password manager in 2024?', solutions: ['Bitwarden - Open source, free tier', '1Password - User-friendly, family plans', 'LastPass - Free tier available', 'Dashlane - VPN included in premium', 'KeePass - Completely offline and free'] }
    ],
    health: [
        { title: 'How to start running as a complete beginner?', solutions: ['Follow Couch to 5K program', 'Get proper running shoes fitted', 'Start with walk/run intervals', 'Run 3 times per week with rest days', 'Focus on time not distance initially'] },
        { title: 'Best exercises to build chest muscles?', solutions: ['Barbell bench press - compound movement', 'Dumbbell flyes - isolation exercise', 'Push-ups - bodyweight foundation', 'Incline bench press - upper chest', 'Dips - lower chest and triceps'] },
        { title: 'How to get rid of belly fat?', solutions: ['Create calorie deficit through diet', 'Strength training 3-4x per week', 'HIIT cardio 2-3x per week', 'Reduce sugar and processed foods', 'Be patient - spot reduction is a myth'] },
        { title: 'Best protein powder for muscle gain?', solutions: ['Optimum Nutrition Gold Standard Whey', 'MyProtein Impact Whey - best value', 'Isopure Zero Carb - low calorie', 'Orgain Organic - plant-based option', 'Dymatize ISO100 - fast absorption'] },
        { title: 'How to fix bad posture from desk work?', solutions: ['Strengthen back muscles with rows', 'Stretch chest and hip flexors daily', 'Practice wall angels exercise', 'Set hourly posture check reminders', 'Consider physical therapy consultation'] }
    ],
    career: [
        { title: 'How to ask for a promotion at work?', solutions: ['Document your achievements and impact', 'Schedule formal meeting with manager', 'Research market rates for your role', 'Present clear case with evidence', 'Ask what\'s needed if not ready yet'] },
        { title: 'Best way to learn new skills while working full-time?', solutions: ['Wake up 1 hour early for focused learning', 'Use lunch breaks for online courses', 'Weekend projects to apply new skills', 'Pomodoro technique after work', 'Join online communities for accountability'] },
        { title: 'How to deal with toxic coworker professionally?', solutions: ['Document everything - emails, incidents, dates', 'Set clear boundaries, keep interactions brief', 'Focus on your work, avoid gossip', 'Talk to manager with specific examples', 'Consider internal transfer if nothing changes'] },
        { title: 'Should I quit my job without another offer?', solutions: ['Generally NO - unless health/safety at risk', 'Save 6-12 months expenses first', 'Try negotiating sabbatical or reduced hours', 'Line up freelance work before quitting', 'Talk to therapist if burnout - might just need vacation'] },
        { title: 'How to stand out in job interviews?', solutions: ['Research company deeply - products, culture, news', 'Prepare STAR stories for common questions', 'Ask smart questions about team and challenges', 'Send thank-you email within 24 hours', 'Bring portfolio or project examples'] }
    ],
    finance: [
        { title: 'Best investment strategy for complete beginners?', solutions: ['Index funds: VTI or VOO, low fees', 'Max out 401k employer match first', 'Open Roth IRA: $6500/year tax-free growth', 'Build emergency fund first: 3-6 months expenses', 'Dollar-cost averaging: invest consistently monthly'] },
        { title: 'How to pay off credit card debt fast?', solutions: ['Avalanche method: highest interest first', 'Balance transfer to 0% APR card', 'Debt consolidation loan at lower rate', 'Side hustle: DoorDash, freelance work', 'Cut expenses: cancel subscriptions, cook at home'] },
        { title: 'Is buying a house worth it in 2024?', solutions: ['Depends on location and 5+ year plans', 'Rent if: high rates, uncertain job, want flexibility', 'Buy if: stable income, good down payment, settling', 'Calculate: mortgage+taxes+maintenance vs rent+investing', 'Consider house hacking: rent out rooms'] },
        { title: 'Best budgeting app that actually works?', solutions: ['YNAB - envelope method, $99/year', 'Mint - Free, automatic tracking', 'Personal Capital - Free, great for investments', 'EveryDollar - Dave Ramsey method', 'Google Sheets - Full control, free templates'] },
        { title: 'How much should I save for retirement?', solutions: ['Rule of thumb: 15% of gross income', 'By age 30: 1x salary, 40: 3x, 50: 6x, 67: 10x', 'Use retirement calculator for your situation', 'Max 401k ($22,500) + Roth IRA ($6,500) if possible', 'Start NOW - compound interest is powerful'] }
    ],
    education: [
        { title: 'Best free online courses for career change?', solutions: ['Google Career Certificates - IT, Data, PM', 'freeCodeCamp - Web development, 300+ hours', 'CS50 Harvard - Computer Science fundamentals', 'Coursera - Audit courses free, pay for certificate', 'YouTube channels: Traversy Media, Fireship'] },
        { title: 'How to study effectively for exams?', solutions: ['Active recall: test yourself vs re-reading', 'Spaced repetition: Anki flashcards', 'Pomodoro: 25 min focus, 5 min break', 'Feynman technique: explain simply', 'Practice problems over theory'] },
        { title: 'Is a coding bootcamp worth $15k?', solutions: ['YES if: career switcher, need structure, good placement rate', 'NO if: self-motivated, can learn free, tight budget', 'Check outcomes: graduation rate, job placement, salaries', 'Try free resources first: freeCodeCamp, Odin Project', 'Consider ISA - pay after getting job'] },
        { title: 'Best way to learn a new language fast?', solutions: ['Immersion: change phone language, watch shows', 'Duolingo daily + Anki for vocabulary', 'iTalki - practice with native speakers $10-15/hr', 'Watch YouTube in target language', 'Don\'t focus on grammar early, prioritize speaking'] },
        { title: 'How to remember what you read in books?', solutions: ['Take notes while reading, summarize chapters', 'Highlight + review within 24 hours', 'Teach concepts to someone else', 'Spaced repetition: review after 1 day, 1 week, 1 month', 'Apply immediately in real life or projects'] }
    ],
    lifestyle: [
        { title: 'Best cities for remote workers in 2024?', solutions: ['Lisbon, Portugal - Affordable, great weather, digital nomad visa', 'Medellín, Colombia - Low cost, spring weather year-round', 'Chiang Mai, Thailand - Very cheap, nomad community', 'Austin, Texas - No state tax, tech hub', 'Barcelona, Spain - Culture, beaches, coworking spaces'] },
        { title: 'How to maintain work-life balance with remote job?', solutions: ['Separate workspace: dedicated room or corner', 'Strict schedule: 9-5 then close laptop', 'Physical transition: walk after work to "commute"', 'Use different browser profiles for work/personal', 'Schedule personal time like meetings'] },
        { title: 'Best morning routine for productivity?', solutions: ['Wake 6am, no phone for 1 hour, hydrate', 'Cold shower, meditation 10 min, healthy breakfast', 'Plan top 3 priorities for day', 'Sunlight exposure within 30 min of waking', 'Journal 5 min: gratitude, goals, intentions'] },
        { title: 'How to make friends in a new city as an adult?', solutions: ['Meetup.com - hobby groups, sports leagues', 'Bumble BFF - dating app for friendships', 'Coworking spaces - even if remote', 'Volunteer - animal shelter, food bank', 'Say yes to everything first 3 months'] },
        { title: 'Best way to declutter and organize home?', solutions: ['KonMari method: keep only what sparks joy', 'One room at a time, complete before moving on', 'Four boxes: keep, donate, sell, trash', 'One in, one out rule for new purchases', 'Digital declutter: unsubscribe emails, delete apps'] }
    ],
    relationships: [
        { title: 'How to maintain long-distance relationship?', solutions: ['Video call daily even if short, schedule date nights', 'Send surprise gifts, handwritten letters', 'Have end goal: when will distance end?', 'Share daily life: photos, voice messages', 'Visit regularly: alternate who travels'] },
        { title: 'Best way to resolve conflicts with partner?', solutions: ['Use "I feel" statements, not "You always"', 'Listen to understand, not to respond', 'Take 20 min break if too heated', 'Focus on solution, not winning', 'Apologize sincerely when wrong'] },
        { title: 'How to make friends as an introvert?', solutions: ['Quality over quantity: 2-3 deep friendships', 'One-on-one hangouts vs group events', 'Online communities first: Discord, Reddit', 'Shared activities: book club, hiking, gaming', 'Be honest about needing alone time'] },
        { title: 'Signs you should break up with someone?', solutions: ['You feel worse about yourself with them', 'Constant criticism, disrespect, or control', 'Different life goals: kids, marriage, location', 'Staying out of fear or comfort, not love', 'Trust is broken and can\'t be rebuilt'] },
        { title: 'How to set boundaries with family?', solutions: ['Be clear and specific about boundaries', 'Enforce consequences consistently', 'Don\'t JADE: Justify, Argue, Defend, Explain', 'Reduce contact if needed', 'Therapy helps handle guilt'] }
    ],
    travel: [
        { title: 'Best budget travel destinations in 2024?', solutions: ['Vietnam - $30/day, amazing food, beautiful beaches', 'Portugal - Cheapest Western Europe', 'Mexico - Close to US, $40/day, incredible culture', 'Thailand - $25/day, islands, temples, street food', 'Albania - Hidden gem Europe, very affordable'] },
        { title: 'How to pack light for 2-week trip?', solutions: ['Capsule wardrobe: 3 tops, 2 bottoms, 1 jacket', 'Wear heaviest items on plane', 'Packing cubes for organization', 'Travel-size toiletries, buy shampoo at destination', 'One bag rule: carry-on only'] },
        { title: 'Best travel credit card for beginners?', solutions: ['Chase Sapphire Preferred - 60k points bonus', 'Capital One Venture - Simple 2x miles', 'Amex Gold - 4x on dining and groceries', 'Citi Premier - 3x on travel, gas, groceries', 'Start with no annual fee: Discover It'] },
        { title: 'How to find cheap flights?', solutions: ['Google Flights - set price alerts, flexible dates', 'Book Tuesday/Wednesday, fly Tuesday/Wednesday', 'Incognito mode - airlines track searches', 'Scott\'s Cheap Flights / Going.com - email alerts', 'Be flexible: nearby airports, layovers, off-season'] },
        { title: 'Is travel insurance worth it?', solutions: ['YES for: international trips, expensive bookings', 'NO for: domestic weekend trips, refundable bookings', 'Check credit card benefits first', 'World Nomads or SafetyWing for long-term', 'Read fine print: pre-existing conditions coverage'] }
    ]
};
